image: Visual Studio 2017
platform:
  - x64
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 8 x64
  - npm install
build_script:
  - npm run dist
test: off
shallow_clone: true
